### ISSUE TITLE
More accurate temperature readings

### ISSUE THREAD

**Issue by scheric** [costastf/toonapilib#13]
If i compare the new api code and the old api code i can see a difference in current temperature readings. The old code is much more precise then the new code.

old:
`return float(self.thermostat_info.current_temperature / 100)`
new:
`return float(self.thermostat_info.current_displayed_temperature / 100)`

Is there a reason that that the temperature readings cant be exact. because the new https://api.toon.eu does not support it anymore.

> I have tried to change the new one to get precise temperature reading but i failed. is it actually possible?

**Comment by scheric** [comment]
You cant get more accurate themperture readings.
if you look at https://developer.toon.eu/api-intro

the new toonapi will only result:
```
 {
    "currentSetpoint": 1050, 
    "currentDisplayTemp": 2150, 
    "programState": 0, 
    "activeState": -1, 
    "nextProgram": -1, 
    "nextState": -1,
    "nextTime": 0, 
    "nextSetpoint": 0, 
    "errorFound": 255, 
    "boilerModuleConnected": 1, 
    "realSetpoint": 1050, 
    "burnerInfo": "0", 
    "otCommError": "0", 
    "currentModulationLevel": 0, 
    "haveOTBoiler": 0 
}
```
So we can only retrieve less accurate temperature readings.

**Comment by JanBoos** [comment]
I found probably 1 error in toonapilib.py. I think that the conversion of toon.temperature has to be (i got only temperatures 19, 20, 21 instead of 19, 19.5, 20, 20.5, 21):
float (toon.temperature) / 100
in stead of:
float (toon.temperature / 100)
