### ISSUE TITLE
Support for webhooks

### ISSUE THREAD

**Issue by JKorf** [costastf/toonapilib#16]
Hi, 

Thanks for your API. I was wondering if you have any plans to implement to webhooks provided by the API so that updates get pushed, rather than having to poll?
https://developer.toon.eu/toonapi/apis/post/%7BagreementId%7D/webhooks

**Comment by scheric** [comment]
It would be nice to have. because the toonapi is sometimes not available for polling.

**Comment by costastf** [comment]
I will look into this next weekend guys. I already spent quite some time to update the current version and fix a couple of small things. Please be patient. Of course PRs are more than welcome :)

**Comment by costastf** [comment]
Hi all (4 of you). How do you imagine the interface being for this implementation?
would something like
```
toon.register_webhook(application_id, callback_url, subscription_time, device_id, subscribed_actions)
``` 
suffice?

**Comment by JKorf** [comment]
Hi, for me that would be fine yes :)

**Comment by michelscholte** [comment]
Great api. I used it for 2 weeks now and it works perfect. Hopefully you get the webhooks working. Thanks for your effort in these.

**Comment by costastf** [comment]
Hi all. I do not use webhooks and setting something up is a bit of a drag just to get this working. Would someone with a usage case be interested in helping out with this? I have created https://github.com/costastf/toonapilib/tree/webhooks which implements gettting of existing webhooks and code that should work for setting and deleting webhooks. If someone can test these and provide feedback on the response of getting the webhooks I can model them in named tuples and make it nice. Thanks in advance to anyone helping out with this.

**Comment by JKorf** [comment]
Hi @costastf , 

I've done some initial testing, here is the output I received:
add_webhook: `204 without content`
delete webhooks: `204 without content`
get webhooks:
`b'[ {\n  "applicationId" : "Test",\n  "callbackUrl" : "https://127.0.0.1:80/toon",\n  "clientUuid" : "yA9LDA6ZNyqVXGc3pUi0HCnDPsdT",\n  "subscriptionTime" : 1551703283765,\n  "subscribedActions" : [ "Thermostat", "SmartPlug", "SmokeDetector", "BoilerErrorInfo" ]\n} ]'`

Note that the add_webhook method requires all parameters at the moment, but only the application_id and callback_url are required. Also, you forgot a json.dumps() call on the payload before sending the request. 

By the way, do you know if the callback url is supposed to be an ip address you're listening on or can it be a local path or anything?

Thanks for your work!

**Comment by costastf** [comment]
Hi @JKorf . I don't think that the callback can be a local url and that is why this is a bit of an overhead for me. It has to be a public reachable url or else this whole thing does not make any sense. Would you be comfortable with making an PR for this?

**Comment by JKorf** [comment]
Hi @costastf, sorry for the late reaction. I'm currently busy with some other stuff, and the callback needing to be a public url is a bit of an issue for where I intend to use it. So maybe someone else might take a look at fixing this in a PR.

**Comment by costastf** [comment]
Hi Jan,
No worries, it is the same with me, i get it. Maybe some one with some skin
in the game here will make a PR for this feature.

kind regards
Costas

**Comment by costastf** [comment]
Closing this as it is a bit stale by now. If anyone is interested in implementing this as described please reopen.
