### ISSUE TITLE
Float issue toon.temperature

### ISSUE THREAD

**Issue by JanBoos** [costastf/toonapilib#19]
I found probably 1 issue in toonapilib.py. I think that the conversion of toon.temperature has to be (i got only temperatures 19, 20, 21 instead of 19, 19.5, 20, 20.5, 21):

float (toon.temperature) / 100

instead of:

float (toon.temperature / 100)

**Comment by costastf** [comment]
Hi, this should be fixed with v3.0.4, thanks for reporting!
