### ISSUE TITLE
Costs are always 0.0 (except for Gas)

### ISSUE THREAD

**Issue by frenck** [costastf/toonapilib#22]
As far as I'm able to tests, costs are always returning 0.0, except for Gas.

Not sure if this is an issue with the library or Toon itself...

```json
{
    ...
    'powerUsage': {
        ...
        'value': 1754,
        'dayCost': 0.0,
        ...
    },
    'gasUsage': {
        'value': 7,
        'dayCost': 1.25,
        ...
    },
    ...
}
```

**Comment by frenck** [comment]
Seems to be related to the API in this case, since a bare request to the API, returns the same.

This is just weird, are you familiar with this issue?

**Comment by costastf** [comment]
This is not an issue with the library, but with the api not returning proper data. 
True enough, 
```
toon.power.daily_cost
0.0
```
```
toon.gas.daily_cost
2.15
```

**Comment by costastf** [comment]
Not much that can be done here, maybe raise an issue with toon development https://developer.toon.eu/contact?

**Comment by frenck** [comment]
I agree this is not the libraries fault, nevertheless, thanks for confirming the same issue. It excludes me as the problem 👍

**Comment by scheric** [comment]
It is definitely not the libraries fault. I looked at it yesterday and saved the data. it was there. 
Right now it is: `0`

note: Look at the `dayUsage` value that is `0`to. Yesterday it was not `0`

***
### look at the files for data
Yesterday: 
![data yesterday](https://user-images.githubusercontent.com/38077357/53290342-d936fd00-37a2-11e9-9e5c-ac156e8f55c5.PNG)



Today: 
![data today](https://user-images.githubusercontent.com/38077357/53290341-d63c0c80-37a2-11e9-96d3-495c890a4a82.PNG)

**Comment by scheric** [comment]
I think they are only using the high tariff power consumption in their calculations.
I have send them an email. If there are results they will be here.

**Comment by scheric** [comment]
I got an answer back from `devsupport@toon.eu ` 

> mesage  is forwarded to the developer team for further investigation.

**Comment by costastf** [comment]
That didn't even take two months 😃
