### ISSUE TITLE
Additional headers required

### ISSUE THREAD

**Issue by NikolasOrtlieb** [costastf/toonapilib#34]
https://github.com/costastf/toonapilib/blob/60f7851fa94ad31a63e157f33b36596123b6e8ba/toonapilib/toonapilib.py#L158

Hi there,
in the near future, we here at Quby will switch our Identity Manager. With this change we will also introduce more security validations on our api's. This means, that in the future, exact date not yet clear, you will need to send two additional headers on each API call. Not on the oAuth or /agreements call though.

Those headers are:

X-Common-Name : {displayCommonName}
X-Agreement-ID : {agreementID}

If you could already add them, it will reduce the possibility that others which use your library will be impacted when this happens.

Thanks
Nikolas

**Comment by costastf** [comment]
Fixed with v3.2.3. Thanks! Much appreciated!
