### ISSUE TITLE
IncompleteStatus error

### ISSUE THREAD

**Issue by reinder83** [costastf/toonapilib#37]
Since today I started getting these errors:

```toonapilib.toonapilibexceptions.IncompleteStatus: {'gasUsage': {'avgDayValue': 560.0, 'dayCost': 0.35, 'value': 0, 'isSmart': 0, 'avgValue': 23.33, 'meterReading': 4061210, 'dayUsage': 470, 'lastUpdatedFromDisplay': 1559829811483}, 'deviceStatusInfo': {'lastUpdatedFromDisplay': 1559829001217, 'device': [], 'inSwitchAllTotal': {'avgUsage': 0.0, 'dayUsage': 0.0, 'currentState': 0, 'currentUsage': 0.0}}, 'powerUsage': {'avgDayValue': 6805.0, 'value': 154, 'maxSolar': 0, 'valueProduced': 0, 'lastUpdatedFromDisplay': 1559830755365, 'meterReading': 10634077, 'isSmart': 0, 'meterReadingLowProdu': 0, 'dayCost': 0.77, 'meterReadingProdu': 0, 'avgValue': 283.54, 'valueSolar': 0, 'dayLowUsage': 1499, 'lowestDayValue': 154, 'avgProduValue': 0, 'dayUsage': 3838, 'meterReadingLow': 9051843, 'solarProducedToday': 0}, 'lastUpdateFromDisplay': 1559830830382, 'thermostatInfo': {'currentDisplayTemp': 2500, 'otCommError': '0', 'burnerInfo': '0', 'activeState': 3, 'boilerModuleConnected': 1, 'nextTime': 0, 'nextProgram': -1, 'nextSetpoint': 0, 'realSetpoint': 1500, 'errorFound': 255, 'hasBoilerFault': 0, 'haveOTBoiler': 1, 'currentModulationLevel': 59, 'nextState': -1, 'lastUpdatedFromDisplay': 1559830808106, 'currentSetpoint': 1500, 'programState': 0}}```

Traceback:
```2019-06-06 14:20:31 ERROR (MainThread) [homeassistant.components.climate] toon: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/toonapilib/toonapilib.py", line 352, in _get_status_value
    output = self.status[value]
KeyError: 'thermostatStates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/toon/climate.py", line 120, in update
    if self.toon.thermostat_state is None:
  File "/srv/homeassistant/lib/python3.5/site-packages/toonapilib/toonapilib.py", line 467, in thermostat_state
    state = self.get_thermostat_state_by_id(current_state)
  File "/srv/homeassistant/lib/python3.5/site-packages/toonapilib/toonapilib.py", line 441, in get_thermostat_state_by_id
    return next((state for state in self.thermostat_states
  File "/srv/homeassistant/lib/python3.5/site-packages/toonapilib/toonapilib.py", line 418, in thermostat_states
    states = self._get_status_value('thermostatStates').get('state', [])
  File "/srv/homeassistant/lib/python3.5/site-packages/toonapilib/toonapilib.py", line 354, in _get_status_value
    raise IncompleteStatus(self.status)
```

I am using this with home assistant
First I thought maybe my library is outdated, so I just upgraded home assistant to the latest version, same issue is still there.

Maybe the ToonAPI changed their output, since I see single quotes in the json, which should be double quotes? since I see this error is raised when there is an json error https://github.com/costastf/toonapilib/blob/c201b85b7c634236093749f142c247ad84581864/toonapilib/toonapilib.py#L253

**Comment by costastf** [comment]
The key thermostatStates is missing. That either means that their api does not send a full status due to errors, or that they have changed the way it responds. Is the error consistent?

**Comment by reinder83** [comment]
Tried several times today, will try again tonight to see what's the response

**Comment by reinder83** [comment]
Keep getting the same error, tried totally removing the integration from HA and adding again, same result, tried turning on program on the toon itself, no result

**Comment by costastf** [comment]
I can validate the issue. It seems that they have changed their payload on the response. The problem is that I will not have time to work on this before monday as a best case scenario.

**Comment by costastf** [comment]
And on another try it works fine.. :(

**Comment by reinder83** [comment]
Nice, so they made a change to their API, that randomly changes the output 😂

**Comment by reinder83** [comment]
#38 Created pull request for this

**Comment by costastf** [comment]
Accepted the MR and made and uploaded new release v.3.2.4. My guess on this is as quby is trying to scale they have started to migrate stuff to more endpoints doing this on a green blue type of fashion but the backend endpoints are incompatible. So depending on the backend that services you, you either get the old response or the new. That is just a guess of course. Thanks for the contribution!
