### ISSUE TITLE
Toon in combination of Stadswarmte

### ISSUE THREAD

**Issue by SteGe88** [costastf/toonapilib#39]
I'm using the Toon in combination of Stadswarmte. Instead of gas I'm using heat consumption which is read by the P1 reader of Toon (same as for the gas meter). 

Is there an option to read this information from Toon?

**Comment by costastf** [comment]
I am sorry, but i have no clue. The implementation is actually utilizing the official toon api. If the service you mention uses that then I guess you could use the library to get your values, if not then certainly not. Sorry for not being to give you a clearer answer.

**Comment by SteGe88** [comment]
Thanks constastf, I have checked the API of toon and indeed, the info is not given by the API. So unfortunately nothing to do about it.

Your answer was clear enough though.
