### ISSUE TITLE
Agreement number

### ISSUE THREAD

**Issue by kvandt** [costastf/toonapilib#4]
Hi Costas, Thanks for your quick action on the tenant_id!! Just another tweak to make the lib even more universal: Can you also make the agreement number (_self.agreement = self.agreements[0]_) as a parameter? This is needed if you have more than one display. Default it is 0, but if you have 2 displays you need to set it to 1 to get the second display. Thnx!

**Comment by costastf** [comment]
Hi @kvandt . Not sure what you mean. Could you please elaborate a bit, possibly with a small code sample and some more explanation on the usage case?

**Comment by kvandt** [comment]
Hi @costastf, the idea of the line self.agreement = self.agreements[0] is to be able to select an agreement. Normally people do have only one, so default is the first (=0). But if you have multiple Toon's, (for example if you have one in a holidayhouse), you can select the second agreement (self.agreement = self.agreements[1]). I know this will not be the most frequently used option, but I can use it myself very well ;-)

I already use this with the deprecated toonlib, which works perfectly (I change the 0 into a 1 in code...)

**Comment by costastf** [comment]
Hi @kvandt . Sorry I was not very clear. The idea is very clear. I was mostly asking about what would be a friendly interface for implementing it. Assigning indexes is hardly friendly. So for example would something like toon.switch_agreement() that would rotate through the agreements be nice? Or maybe something like toon.enable_agreement(specific_agreement_something) ? This is trivial to implement and of course I will implement it, there is no use case too small :)

**Comment by kvandt** [comment]
Hi @costastf, you could use  
https ://developer.toon.eu/toonapi/apis/get/agreements to show available agreements. Maybe only when more than 1 you could raise a question to the user. Since the chance for having two Toons is not very large, you could start with just using default 0 and take it as an optional parameter which can be documented. Only thing is to check if a chosen agreement is existing and report to the user if not.

**Comment by costastf** [comment]
Hi @kvandt, showing the user an interactive question does not fit in the context of a library. Since you have two agreements could you please tell me if their ids are unique? If that is the case then I will implement a toon.enable_agreement_by_id(agreement_id) with which the active agreement can be changed.

**Comment by kvandt** [comment]
@costastf  Yes off course you can't introduce an interactive part in a library....
The agreement_id's are unique, but these do not make sense to anything I can see from the display. A displayCommonName would make more sense since you can find this in the display (and on the back of the display).

But anyhow, just the option to enter a different agreement index (>0) would be perfect, where it defaults to 0 for the majority.

**Comment by kvandt** [comment]
Hi Costastf, is the simple agreement index as parameter something you can implement? I would suggest to keep it simple now. I hope this can be included the moment ToonHA (and your library) will be updated in Home-Assistant. Thnx!

**Comment by costastf** [comment]
Hi @kvandt . I have implemented an optional enabled_agreement_id argument where you can set the agreement you want enabled, a method enable_agreement_by_id(agreement_id) with which you can switch agreements and a property of agreements_ids to be able to see the ids of your agreements. I hope this is ok for you, so closing this and I will ask @Boltgolt if he would be so kind as to implement the optional argument in ToonHA.

**Comment by kvandt** [comment]
Cool, will try asap. Looking at the code, it would have been much easier to have just the index number (default 0 but 1 in my case) as parameter. This would only require the line `self.agreement = self.agreements[0]` to something `self.agreement = self.agreements[agreement_index]` where agreement_index is put in the optional parameters, defaulting to 0. As mentioned before the agreement_id value cannot be seen from the display and not be guessed. The agreement_index is 0 for the first agreement and 1 for second, etc. So it's easier to try.

**Comment by costastf** [comment]
Hi @kvandt, apologies for the late reply but I have been really busy. Accessing by index might seem easier but code design wise it is a very poor design. It is very error prone and does not mean anything semantically to the user. Index 0 and index 1 curry no information on what the underlying system does. That is why I expose an attribute of agreement_ids so the ids can be retrieved and since they are unique and do not change and actually curry the information required are the ones that should be used. Once you have retrieved them once you can then know that id "blah" is this house and id "blah2" is that house and you can initialize the instance accordingly per house by passing the appropriate id. I hope that this makes sense and that the library is useful to you.

**Comment by kvandt** [comment]
Hi @costastf, in that case it would be much nicer to expose the "displayCommonName" as indicator. This is also a unique identifier. This value can be seen from the display (both in the UI as on the back of the display). You can just enter "eneco-001-xxxxxx" to select the correct display to connect to.

**Comment by kvandt** [comment]
Nice work @costastf !
