### ISSUE TITLE
Don't monkey patch requests

### ISSUE THREAD

**Issue by balloob** [costastf/toonapilib#40]
This lib monkey patches requests ([source](https://github.com/costastf/toonapilib/blob/master/toonapilib/toonapilib.py#L283-L311)). But it looks like all the code that calls `requests.get` can be safely updated to just call `self._patched_request` directly. The monkey patch is than no longer necessary.

**Comment by costastf** [comment]
Just uploaded v3.2.5 that removes the monkey patching.
