### ISSUE TITLE
New authentication method. Is this compatible?

### ISSUE THREAD

**Issue by stephanvdplas** [costastf/toonapilib#44]
in developer.toon.eu/authentication, there is a statement about new authentication:

From December 2019 onwards, Eneco users are required to use the “mijn Eneco” login to access their Toon, use the following call from the application to use the “mijn Eneco” as identity source:

curl -v -k
    https://api.toon.eu/authorize?response_type=code
        &redirect_uri=<redirect_url>
        &client_id=<consumer_key>
        &issuer=identity.toon.eu
        &tenant_id=eneco
From the ToonAPI website's login page, the end user needs to provide his credentials. A redirect will then be performed to the redirect_uri provided before with a code. The application can now use that code and the application key pair to get an access token that looks like this:

curl -k -X POST 
    -H "Content-Type: application/x-www-form-urlencoded"
    -d  "client_id=<consumer_key>
        &client_secret=<consumer_secret>
        &grant_type=authorization_code
        &redirect_uri=<redirect_uri>
        &tenant_id=eneco
        &code=<code>"
    https://api.toon.eu/token 

Again, in this call, when users have logged in via "Mijn Eneco", add the issuer to this request:

curl -k -X POST 
    -H "Content-Type: application/x-www-form-urlencoded"
    -d  "client_id=<consumer_key>
        &client_secret=<consumer_secret>
        &grant_type=authorization_code
        &issuer=identity.toon.eu
        &redirect_uri=<redirect_uri>
        &tenant_id=eneco
        &code=<code>"
    https://api.toon.eu/token 

Is the ToonApiLib compatible with this?

**Comment by costastf** [comment]
Just released version 4 which implements this new authentication method.
