### ISSUE TITLE
Issue with new authentication method

### ISSUE THREAD

**Issue by wtrdk** [costastf/toonapilib#46]
Hi,

I just updated my toonapilib, and tried the new authentication method. I followed the instructions in the docs, and changed:

`toon=Toon(eneco_username, eneco_password, consumer_key, consumer_secret)`

to

`toon = Toon(token)`

I set the token variable to the token I got from https://api.toon.eu/toonapi-accesstoken and I get the following error:

`    toon=Toon(token)
TypeError: __init__() missing 3 required positional arguments: 'eneco_password', 'consumer_key', and 'consumer_secret' `

My script:
```
from toonapilib import Toon

token = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'

toon=Toon(token)

print("gas_daily_usage: ", toon.gas.daily_usage)
print("power_daily_usage_low: ", toon.power.daily_usage_low)
print("power_daily_usage: ", toon.power.daily_usage)
print("thermostat: ", toon.thermostat)
print("temperature: ", toon.temperature)
print("gas_meter_reading: ", toon.gas.meter_reading)
print("power_meter_reading_low: ", toon.power.meter_reading_low)
print("power_meter_reading: ", toon.power.meter_reading)
print("power_value: ", toon.power.value)
print("gas_value: ", toon.gas.value)
```

What am I doing wrong? Thanks!

**Comment by costastf** [comment]
You are not using the updated library. Your system is still using the old
one that expects 4 arguments.

**Comment by wtrdk** [comment]
I upgraded toonapilib using `pip install --upgrade toonapilib` and the upgrade succeeded:
`Successfully installed backoff-1.9.2 cachetools-3.1.1 certifi-2019.11.28 chardet-3.0.4 coloredlogs-10.0 dateparser-0.7.2 humanfriendly-4.18 idna-2.8 monotonic-1.5 python-dateutil-2.8.1 pytz-2019.3 regex-2019.11.1 requests-2.22.0 six-1.13.0 toonapilib-4.1.0 tzlocal-2.0.0 urllib3-1.25.7`

Still no luck, I get the same error...

**Comment by costastf** [comment]
I am afraid that it might not be that simple. The message mentions
successfully installed libraries, but no mention of upgrade. Python has the
notion of virtual environments which are isolated environments and you
might be installing things in a context but not executing from the same
context. In order for me to help i would need to know which
python interpreter you are using, and how you are using the library. Please
give me the output of :
$ which python
$ which pip

and then copy paste exactly how it is your using the library for me to
understand how things are set up.

**Comment by wtrdk** [comment]
Thanks for your fast responses!

In the previous post you can see version 4.1.0 of toonapilib seems to be installed, so that should be okay.

When I run `which` I get an error, that's why I run `/usr/bin/which`
`/usr/bin/which pip`
`/usr/bin/pip`

`usr/bin/which python`
`/usr/bin/python`

`pip -V`
`pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)`

I've got both python 2.7 and python 3 installed, and I use python3 to run the script (e.g. `python3 toon.py`)

I've created a python script, copied in my first post,  to get some data from Toon. This script used to run fine up until the 1st of December, due to the changed authentication method. I'm trying to get it to work again. This script is just run from my home directory on an Ubuntu 18.04 machine.

**Comment by costastf** [comment]
Right, but you installed it in python2.7 because there is where your pip is
pointing at so you are still using the old one that you have installed in
your python3.7 environment. So try pip3 install toonapilib and try again.
After now, I will not be responding so quick, i am afraid my time is up :)
Please keep me posted with how it went and if you need any more help, I
will probably be able to answer in the afternoon.

**Comment by wtrdk** [comment]
AARGH! I feel so stupid! That was it! I had to install it with pip3.
So sorry to waste your time! Thanks a lot!

**Comment by costastf** [comment]
No worries, the python ecosystem can get quite confusing ;)
