### ISSUE TITLE
Decimals for temperature

### ISSUE THREAD

**Issue by wtrdk** [costastf/toonapilib#5]
Hi,

Thanks for this nice piece of software.
When I use the API of Domoticz to fetch the actual roomtemperature from my Toon Thermostat I get decimals in the range of 0-9, like so:
19,1 - 20,2 - 21,7
When I use the script in this repo I only get decimals 0 or 5, like so:
19,0 - 20,5 - 21,5

Does the current Toon api not provide the exact temperature? What is the difference with the Domoticz API?

**Screenshot from Domoticz:**
<img width="900" alt="schermafbeelding 2018-02-20 om 20 27 19" src="https://user-images.githubusercontent.com/4569244/36444812-975a4312-167c-11e8-898d-bde229db075f.png">

**Screenshot from MySQL with both Domoticz and Toonapilib data:**
![schermafbeelding 2018-02-20 om 20 31 32](https://user-images.githubusercontent.com/4569244/36445089-7a1663e8-167d-11e8-984c-730a05ba2313.jpg)

**Comment by boltgolt** [comment]
I recall this being a thing back on the old API, i think i even asked if it changed on the ToonHA forum thread at some point. 

We switched from an unofficial, reverse engeneered API from the Toon app to the official one. Do you need to give a client secret and a client token in the Domoticz component?

**Comment by wtrdk** [comment]
In Domoticz you only have to provide the Toon credentials, no secret, token or API key.
I thought the old API to communicate with Toon was deprecated. I'm not sure in what way Domoticz communicates with Toon.

**Comment by boltgolt** [comment]
Then it's using the API from the app, or other unofficial methods. I don't believe we round it to the nearest .5 anywhere so this library simply can't get the more detailed data because the API doesn't offer it. @costastf can you confirm that the temperature isn't rounded in this library?

**Comment by wtrdk** [comment]
Too bad this isn’t supported in the official API! 
Anyway, keep up the good work! I really like this library.

**Comment by costastf** [comment]
There is no rounding going on. The current set temperature is accurate to the decimal but set the temperature is being done in increments of .5 as with the toon app, and it is how the api supports it.
