### ISSUE TITLE
Error since today

### ISSUE THREAD

**Issue by wtrdk** [costastf/toonapilib#7]
Since monday 16th of april, 20:00 I get this error with all toon scripts:

Traceback (most recent call last):
  File "toon.py", line 10, in <module>
    print("Gas: ",toon.gas.daily_usage)
  File "/home/wtrdk/.local/lib/python3.5/site-packages/toonapilib/toonapilib.py", line 310, in gas
    usage = self.status['gasUsage']
KeyError: 'gasUsage'

Another example:

Traceback (most recent call last):
  File "toon_power.py", line 10, in <module>
    print(toon.power.daily_usage)
  File "/home/wtrdk/.local/lib/python3.5/site-packages/toonapilib/toonapilib.py", line 322, in power
    power = self.status['powerUsage']
KeyError: 'powerUsage'

A friend who also uses the scripts from this repository experiences the same issue, so it is not a local issue.

Were there any changes in the Toon API?

**Comment by wtrdk** [comment]
A friend who also uses the scripts from this repository experiences the same issue, so it is not a local issue.

**Comment by sergeversluis** [comment]
I'm experiencing the same thing.
What's up with that?

Looking forward to a swift resolution because I like this approach.

**Comment by PostSven** [comment]
Samen issue here, i am only able to pull up the agreement parts.

**Comment by costastf** [comment]
v3.0.1 should fix this. I also added a more specific message. Closing this since I think its properly handled. Please try and if there are any issues feel free to reopen.

**Comment by wtrdk** [comment]
> I've upgraded to 3.0.1, but I still experience the same issue:
> 
> `Traceback (most recent call last):
>   File "toon.py", line 10, in <module>
>     print("Gas: ",toon.gas.daily_usage)
>   File "/home/wtrdk/.local/lib/python3.5/site-packages/toonapilib/toonapilib.py", line 310, in gas
>     usage = self.status['gasUsage']
> KeyError: 'gasUsage'`
> 
> Is there anything else that has to be changed after upgrading?

Executing the script in Python 2 does work!. Strange thing is that I never used python2.x with this script before (wasn't installed on my server), only python3. But after installing python2 it works like a charm.

**Comment by costastf** [comment]
How exactly did you upgrade? The code that you mention does not exist in the latest version.

**Comment by wtrdk** [comment]
Already solved, see my previous comment! Thanks!
